apiVersion: v1
kind: Pod
metadata:
  labels:
    app: frontend
  name: myapp3
spec:
  containers:
  - image: nginx:latest
    name: myapp3
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
