apiVersion: v1
kind: Pod
metadata:
  labels:
    run: myapp3
  name: myapp3
spec:
  containers:
  - image: rockylinux:latest
    name: myapp3
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
