apiVersion: v1
kind: Pod
metadata:
  name: myapp5
  namespace: mytg
  labels:
    app: frontend
    env: prod
    version: v1
  annotations:
    aboutpod: "this is dummy pod for practiose"
    owner: "kishan | kishan@gmail.com"
spec:
  containers:
    - name: c1
      image: nginx:latest
      ports:
        - containerPort: 80
  nodeSelector:
    disktype: ssd

  
