apiVersion: v1
kind: Service
metadata:
  name: mynps
  namespace: mytg
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32000
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32001
  selector:
    env: stage
