apiVersion: v1
kind: Pod
metadata:
  labels:
    env: stage
    app: frontend
  name: resource-test
spec:
  containers:
  - image: 933538/repo2026:nginx-v1.0
    name: c2
    resources:
      requests:                          #---minimum resource allocate-----#
        memory: "128Mi"
        cpu: "250m"
      limits:                            #---Manximum resource goes to-------#
        memory: "256Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  - image: 933538/repo2026:nodejs-v1.0
    name: c3
    ports:
      - containerPort: 8080
