apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp500
  name: myapp500
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp500
  strategy: {}
  template:
    metadata:
      labels:
        app: myapp500
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
