apiVersion: v1
kind: Secret
metadata:
  name: mysec
type: opaque
data:
  MYSQL_ROOT_PASSWORD: cmVkaGF0MTIz
  MYSQL_USER: cmVkaGF0 
  MYSQL_PASSWORD: cmVkaGF0NDU2

  #-----| The value entered in Keys(MYSQL_*) are base64 encoded values |-----# 
  #Command to encrypt simple data into base64 encoded is below#
  #------|  echo -n <redhat> |base64  |------#
  #
  #
  #Command to create secret in imperative way is below
  #----|kubectl create secret <secret-type(generic,tls,etc> <secret-name> --from-literal=MYSQL_USER=<encoded-value> -n <mytg>|----#
  #
  #
  #command to decode base64 data given in secret is given below
  #----| kubectl get secret <secret-name> --template={{.data.<key-name>}} | base64 --decode |----#
