apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  namespace: mytg
spec:
  containers:
    - name: mysql
      image: mysql:8
      ports:
        - containerPort: 3306
      env:             #----|secret works on this keyword|----#
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysec
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysec
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysec
              key: MYSQL_PASSWORD



